// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from "zod";
import { Entity, KeyAccessError } from "../../core/engine";
import "../models";
import { SQLiteStore as Store } from "../../core/store";

type SchemaNames;
export const store = new Store<SchemaNames>("", {
});
