// THIS SHOULD BE AN AUTOGENERATED FILE
import { Entity, KeyAccessError } from "./core/engine";

type SeedModel = {
  id: number;
  background: string;
  body: string;
  accessory: string;
  head: string;
  glasses: string;
};

export class Seed extends Entity<SeedModel> {
  get background(): string {
    const value = this.get("background");
    if (!value) {
      throw new KeyAccessError("background");
    }
    return value;
  }

  set background(value: string) {
    this.set("background", value);
  }

  get body(): string {
    const value = this.get("body");
    if (!value) {
      throw new KeyAccessError("body");
    }
    return value;
  }

  set body(value: string) {
    this.set("body", value);
  }

  get accessory(): string {
    const value = this.get("accessory");
    if (!value) {
      throw new KeyAccessError("accessory");
    }
    return value;
  }

  set accessory(value: string) {
    this.set("accessory", value);
  }

  get head(): string {
    const value = this.get("head");
    if (!value) {
      throw new KeyAccessError("head");
    }
    return value;
  }

  set head(value: string) {
    this.set("head", value);
  }

  get glasses(): string {
    const value = this.get("glasses");
    if (!value) {
      throw new KeyAccessError("glasses");
    }
    return value;
  }

  set glasses(value: string) {
    this.set("glasses", value);
  }

  // save(): void {
  //   console.log("persisting to db");
  //   return store.set<T>("seed", this.pk, this.data);
  // }
}

// export class SeedBatch extends Batch<Seed> {}
